In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/new_cleaned_part1.csv")

In [ ]:
df.shape

(10025, 18)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10025 entries, 0 to 10024
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   JobTitle             10025 non-null  object
 1   Company Size         10025 non-null  object
 2   company_Industry     10025 non-null  object
 3   Country              10025 non-null  object
 4   Remote Type          10025 non-null  object
 5   Exp. Level           10025 non-null  object
 6   Years_Experience     10025 non-null  float64
 7   Education  Level     10025 non-null  object
 8   Skills - Python      9405 non-null   object
 9   Skills - SQL         9362 non-null   object
 10  Skills - ML          9369 non-null   object
 11  Skills-DeepLearning  9427 non-null   object
 12  skills_Cloud         9443 non-null   object
 13  Salary (USD)         9408 non-null   object
 14  Posting Month        9414 non-null   object
 15  posting_Year         9373 non-null   object
 16  Hiring Urgency       9399 non-null   object
 17  Job Openings         9406 non-null   object
dtypes: float64(1), object(17)
memory usage: 1.4+ MB

Skills - Python :

1. Completeness issues
2. validation issues like : -1
3. consistency issues : true, false for binary numbers

In [ ]:
df['Skills - Python'].isnull().sum()

np.int64(620)

In [ ]:
df['Skills - Python'].str.lower().unique()

array(['1', '0', 'yes', '2', '-1', 'no', 'true', 'na', nan, 'false',
       'unknown'], dtype=object)

In [ ]:
mapping = {
    '1': 1,
    '0' : 0,
    'yes': 1,
    '2' : 0,
    '-1': 1,
    'no': 0,
    'true': 1,
    'na': 0,
    'nan' : 0,
    'false': 0,
    'unknown' : 0
}

df['Skills - Python'] = df['Skills - Python'].map(mapping)

In [ ]:
df['Skills - Python'] = df['Skills - Python'].fillna(df['Skills - Python'].mode()[0]).astype(int)

In [ ]:
df['Skills - Python'].isnull().sum()

np.int64(0)

In [ ]:
df['Skills - Python'].shape

(10025,)

Skills - SQL:
1. Completeness issues
2. validation issues like : -1
3. consistency issues : true, false for binary numbers

In [ ]:
df['Skills - SQL'].isnull().sum()

np.int64(663)

In [ ]:
df['Skills - SQL'].str.lower().unique()

array(['false', '0', nan, '1', '-1', 'yes', 'na', '2', 'no', 'true',
       'unknown'], dtype=object)

In [ ]:
mapping = {
    '1': 1,
    '0' : 0,
    'yes': 1,
    '2' : 0,
    '-1': 1,
    'no': 0,
    'true': 1,
    'na': 0,
    'nan' : 0,
    'false': 0,
    'unknown' : 0
}

df['Skills - SQL'] = df['Skills - SQL'].map(mapping)

In [ ]:
df['Skills - SQL'] = df['Skills - SQL'].fillna(df['Skills - SQL'].mode()[0]).astype(int)

In [ ]:
df['Skills - SQL'].isnull().sum()

np.int64(0)

In [ ]:
df['Skills - SQL'].shape

(10025,)

Skills - ML:
1. Completeness issues
2. validation issues like : -1
3. consistency issues : true, false for binary numbers

In [ ]:
df['Skills - ML'].isnull().sum()

np.int64(656)

In [ ]:
df['Skills - ML'].str.lower().unique()

array(['0', '1', nan, '2', 'false', 'true', 'no', 'yes', 'na', '-1',
       'unknown'], dtype=object)

In [ ]:
mapping = {
    '1': 1,
    '0' : 0,
    'yes': 1,
    '2' : 0,
    '-1': 1,
    'no': 0,
    'true': 1,
    'na': 0,
    'nan' : 0,
    'false': 0,
    'unknown' : 0
}

df['Skills - ML'] = df['Skills - ML'].map(mapping)

In [ ]:
df['Skills - ML'] = df['Skills - ML'].fillna(df['Skills - ML'].mode()[0]).astype(int)

In [ ]:
df['Skills - ML'].isnull().sum()

np.int64(0)

Skills-DeepLearning :
1. Completeness issues
2. validation issues like : -1
3. consistency issues : true, false for binary numbers

In [ ]:
df['Skills-DeepLearning'].isnull().sum()

np.int64(598)

In [ ]:
df['Skills-DeepLearning'].str.lower().unique()

array(['0', '1', nan, '2', 'no', 'unknown', 'true', 'yes', 'na', 'false',
       '-1'], dtype=object)

In [ ]:
mapping = {
    '1': 1,
    '0' : 0,
    'yes': 1,
    '2' : 0,
    '-1': 1,
    'no': 0,
    'true': 1,
    'na': 0,
    'nan' : 0,
    'false': 0,
    'unknown' : 0
}

df['Skills-DeepLearning'] = df['Skills-DeepLearning'].map(mapping)

In [ ]:
df['Skills-DeepLearning'] = df['Skills-DeepLearning'].fillna(df['Skills-DeepLearning'].mode()[0]).astype(int)

In [ ]:
df['Skills-DeepLearning'].isnull().sum()

np.int64(0)

skills_Cloud :
1. Completeness issues
2. validation issues like : -1
3. consistency issues : true, false for binary numbers

In [ ]:
df['skills_Cloud'].isnull().sum()

np.int64(582)

In [ ]:
df['skills_Cloud'].str.lower().unique()

array(['0', '1', 'yes', 'true', nan, 'no', '-1', '2', 'false', 'na',
       'unknown'], dtype=object)

In [ ]:
mapping = {
    '1': 1,
    '0' : 0,
    'yes': 1,
    '2' : 0,
    '-1': 1,
    'no': 0,
    'true': 1,
    'na': 0,
    'nan' : 0,
    'false': 0,
    'unknown' : 0
}

df['skills_Cloud'] = df['skills_Cloud'].map(mapping)

In [ ]:
df['skills_Cloud'] = df['skills_Cloud'].fillna(df['skills_Cloud'].mode()[0]).astype(int)

In [ ]:
df['skills_Cloud'].isnull().sum()

np.int64(0)

Salary (USD) :
1. Completeness issues
2. validation issues like : many salaries is negative
3. some salary existed with special chars and alphabets
4. Outliers exist
5. accuracy issue - in some records salary is mentioned as 0.0

In [ ]:
df['Salary (USD)'].isnull().sum()

np.int64(617)

In [ ]:
df['Salary (USD)'].unique()

array(['$48,629', '138483', '119038', ..., '101749', '155137', '101450'],
      dtype=object)

In [ ]:
df['Salary (USD)'] = df['Salary (USD)'].str.replace('$',' ').str.strip().str.replace(',','')

In [ ]:
def convert_salary_to_float(salary_str):
    if pd.isna(salary_str):
        return np.nan
    s = str(salary_str).lower().strip()
    if 'k' in s:
        s = s.replace('k', '')
        try:
            return float(s) * 1000
        except ValueError:
            return np.nan
    else:
        try:
            return float(s)
        except ValueError:
            return np.nan

df['Salary (USD)'] = df['Salary (USD)'].apply(convert_salary_to_float)

In [ ]:
def negative_to_positive(price):
  if price < 0:
    return abs(price)
  elif price == np.nan :
    return np.nan
  else:
    return price

In [ ]:
df['Salary (USD)'] = df['Salary (USD)'].apply(negative_to_positive)

In [ ]:
df['Salary (USD)'].sample(5)

3591     83661.0
4373    157679.0
6671    181373.0
3887    112203.0
7711    114501.0
Name: Salary (USD), dtype: float64

In [ ]:
df['Salary (USD)'].isnull().sum()

np.int64(689)

In [ ]:
df['Salary (USD)'].dtype

dtype('float64')

In [ ]:
df['Salary (USD)'].min()
df['Salary (USD)'].max()
df['Salary (USD)'].sum()

np.float64(25924059780.0)

In [ ]:
df['Salary (USD)'].isnull().sum()

np.int64(689)

In [ ]:
Q1 = df['Salary (USD)'].quantile(0.25)
Q3 = df['Salary (USD)'].quantile(0.75)
IQR = Q3 -Q1

lower_value = Q1 - (1.5 * IQR)
print('lower_value', lower_value)
upper_value = Q3 + (1.5 * IQR)
print('upper_value', upper_value)

min = df['Salary (USD)'].quantile(0.05)
lower_value = max(lower_value, min)
print('new', lower_value)

lower_value 15816.75
upper_value 212076.75
new 61004.0

In [ ]:
df['Salary (USD)'] = df['Salary (USD)'].clip(lower=lower_value, upper=upper_value)

In [ ]:
df['Salary (USD)'].fillna(df['Salary (USD)'].median(), inplace=True)

/tmp/ipykernel_14811/4173895069.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary (USD)'].fillna(df['Salary (USD)'].median(), inplace=True)

In [ ]:
df['Salary (USD)'][df['Salary (USD)'] == 0.0].count()
df['Salary (USD)'][df['Salary (USD)'] >= 9999999.0].count()

np.int64(0)

In [ ]:
df['Salary (USD)'].dtype

dtype('float64')

Posting Month :

1. completeness issues
2. consistency issues

In [ ]:
df['Posting Month'].isnull().sum()

np.int64(611)

In [ ]:
df['Posting Month'].unique()

array(['10', '1', 'Nov', '6', '4', '3', '7', nan, '5', 'Jan', '9', '8',
       '0', '2', '11', 'Oct', '12', 'na', '13', 'Sep', 'Mar', 'Feb',
       'Aug', 'Dec', 'Apr', 'UNKNOWN', 'May', 'Jun', 'Jul'], dtype=object)

In [ ]:
mapping = {
    '11': '11', 'Nov': '11',
    '1': '1', 'Jan': '1',
    'Mar': '3', '3': '3',
    'May': '5', '5': '5',
    '6': '6', 'Jun': '6',
    '7': '7', 'Jul': '7',
    '8': '8', 'Aug': '8',
    'Dec': '12', '12': '12',
    'Apr': '4', '4': '4',
    'Oct': '10', '10': '10',
    'Sep': '9', '9': '9',
    'Feb': '2', '2': '2',
    '0': '0',
    '13': '0',
    'UNKNOWN' : '0',
    'na': '0'
}

In [ ]:
df['Posting Month'] = df['Posting Month'].map(mapping)

In [ ]:
df['Posting Month'] = df['Posting Month'].fillna(method='ffill')

/tmp/ipykernel_14811/4165793033.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Posting Month'] = df['Posting Month'].fillna(method='ffill')

In [ ]:
df['Posting Month'] = df['Posting Month'].astype(int)

In [ ]:
df['Posting Month'].value_counts()
df['Posting Month'] = df['Posting Month'].clip(lower=1, upper=12)

In [ ]:
df['Posting Month'].isnull().sum()

np.int64(0)

posting_Year :

1. completeness issues
2. consistency issues

In [ ]:
df['posting_Year'].isnull().sum()

np.int64(652)

In [ ]:
df['posting_Year'].unique()

array(['2024', '2023', '2022', '2025', '2026', '2020', '2021', nan,
       'UNKNOWN', 'na'], dtype=object)

In [ ]:
df['posting_Year'] = df['posting_Year'].fillna(method='bfill')

/tmp/ipykernel_14811/2148000784.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['posting_Year'] = df['posting_Year'].fillna(method='bfill')

In [ ]:
df['posting_Year'].dtype

dtype('O')

In [ ]:
df['posting_Year'] = df['posting_Year'].replace('na', df['posting_Year'].mode()[0])

In [ ]:
df['posting_Year'] = df['posting_Year'].replace('UNKNOWN', df['posting_Year'].mode()[0])

In [ ]:
df['posting_Year'] = df['posting_Year'].astype(int)

In [ ]:
df['posting_Year'].isnull().sum()

np.int64(0)

Hiring Urgency :

1. completeness issues
2. consistency issues

In [ ]:
df['Hiring Urgency'].isnull().sum()

np.int64(626)

In [ ]:
df['Hiring Urgency'].str.lower().str.strip().unique()

array(['not urgent', 'urgent', 'high', nan, 'high priority',
       'low priority', 'low', 'na', 'medium', 'med', 'moderate',
       'unknown'], dtype=object)

In [ ]:
mapping = {
    'unknown' : 'Unknown',
    'not urgent' : 'Low',
    'urgent' : 'High',
    'high' : 'High',
    'high priority' : 'High',
    'low priority' : 'Low',
    'low' : 'Low',
    'na' : 'Low',
    'medium': 'Medium',
    'med' :'Medium',
    'moderate':'Medium'
}

In [ ]:
df['Hiring Urgency'] = df['Hiring Urgency'].map(mapping)

In [ ]:
df['Hiring Urgency'] = df['Hiring Urgency'].fillna(method='ffill')

/tmp/ipykernel_14811/1034826002.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Hiring Urgency'] = df['Hiring Urgency'].fillna(method='ffill')

In [ ]:
df['Hiring Urgency'].value_counts()

Hiring Urgency
High      3981
Low       3661
Medium    2383
Name: count, dtype: int64

Job Openings :

1. completeness issues
2. consistency issues
3. validation issue - job openings can't be negative

In [ ]:
df['Job Openings'].isnull().sum()

np.int64(619)

In [ ]:
df['Job Openings'].unique()

array(['1', '9', '5', '7', '0', '3', '8', 'UNKNOWN', '-8', '4', '6', '2',
       nan, '-7', '-1', '-3', '-5', 'na', '-4', '-6', '-9', '-2'],
      dtype=object)

In [ ]:
df['Job Openings'] = df['Job Openings'].replace(['UNKNOWN', 'na'], np.nan)
df['Job Openings'] = pd.to_numeric(df['Job Openings'], errors='coerce')
df['Job Openings'] = df['Job Openings'].fillna(0)

In [ ]:
df['Job Openings'].isnull().sum()

np.int64(0)

In [ ]:
import pandas as pd
import numpy as np
def negetive_to_positive(num):
  # Check if num is a numeric type (int or float) and is negative
  if isinstance(num, (int, float)) and num < 0:
    return abs(num)
  # Use pd.isna() for robust NaN checking
  elif pd.isna(num):
    return np.nan
  else:
    return num

In [ ]:
df['Job Openings'] = df['Job Openings'].apply(negetive_to_positive)

In [ ]:
df['Job Openings'] = df['Job Openings'].astype(int)

In [ ]:
df['Job Openings'].mean()

np.float64(4.5106234413965085)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10025 entries, 0 to 10024
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   JobTitle             10025 non-null  object
 1   Company Size         10025 non-null  object
 2   company_Industry     10025 non-null  object
 3   Country              10025 non-null  object
 4   Remote Type          10025 non-null  object
 5   Exp. Level           10025 non-null  object
 6   Years_Experience     10025 non-null  float64
 7   Education  Level     10025 non-null  object
 8   Skills - Python      10025 non-null  int64
 9   Skills - SQL         10025 non-null  int64
 10  Skills - ML          10025 non-null  int64
 11  Skills-DeepLearning  10025 non-null  int64
 12  skills_Cloud         10025 non-null  int64
 13  Salary (USD)         10025 non-null  float64
 14  Posting Month        10025 non-null  int64
 15  posting_Year         10025 non-null  int64
 16  Hiring Urgency       10025 non-null  object
 17  Job Openings         10025 non-null  int64
dtypes: float64(2), int64(8), object(8)
memory usage: 1.4+ MB

In [ ]:
df.to_csv('fully_cleaned.csv', index=False)